development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rails_news_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rails_news_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rails_news_production
